### ISSUE TITLE
 request for improvement

### ISSUE THREAD

**Issue by llronaldoll** [ThunderDoesPlugins/WorldTP#5]
make it possible to execute the command through the console please!

**Comment by Thunder33345** [comment]
which commands?
only command that cant be executed by console is
https://github.com/ThunderDoesPlugins/WorldTP/blob/master/src/Thunder33345/WorldTP/WorldTP.php#L55
since it make sense console dont "belong" to a world
i guess i can consider /wtp <folder name> <player name>
if this is what you want, please confirm

next time please kindly explain what you want in detail

**Comment by llronaldoll** [comment]
I would like to add the possibility that the commands are executed by the Itemcommand plugin, but when I try to do this it warns that the command must be executed by a player! exemple= wtp command !

**Comment by Thunder33345** [comment]
you can always run command as the player to tp between worlds
but i will consider /wtp worldname playername so console/ops can tp others

**Comment by Thunder33345** [comment]
@llronaldoll added /worldtpplayer / /wtpp 
usage /wtpp <player> <world>
useful for when you want to TP them but dont want to give them the perms to use /wtp and teleport between worlds freely 

marking this as closed now

**Comment by llronaldoll** [comment]
Good night, I use the ItemCommand plugin which when using an item it executes a command, it happens that your update almost solved my problem, since this plugin executes the command through the console, but I needed your command to select the player automatically with {player } or using the Player selector plugin that uses selectors such as @r @pe etc!

**Comment by Thunder33345** [comment]
sadly that depends on your plugin
if your plugin convert {player} to the playername my plugin should work
but other then relying in other plugins to input data
there's not much i can do
