### ISSUE TITLE
Getting a Nested permissions declarations are no longer supported

### ISSUE THREAD

**Issue by Hacksmith55555** [ThunderDoesPlugins/WorldTP#7]
I don't know if this is an outdated plugin or something but everytime I try to run it I get a nested permissions declarations are no longer supported could I get some help resolving this issue.

**Comment by Thunder33345** [comment]
this plugin was and always had been outdated, it should been impossible to run this plugin on the latest server

see plugin.yml which declared plugin compatibility

https://github.com/ThunderDoesPlugins/WorldTP/blob/master/plugin.yml#L9

unless you modified it yourself the plugin shouldnt been able to start in first place

**Comment by Hacksmith55555** [comment]
So your saying that I just need to down grade my server?

**Comment by Thunder33345** [comment]
> So your saying that I just need to down grade my server?

i am saying this plugin was never made to support the latest API

forcefully editing the api value will not magically make problems go away

**Comment by Thunder33345** [comment]
i no longer maintain PMMP plugins, but if someone want to PR a fix, i will gladly attend to it
